# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI 
 
on: 
  push:
    branches: [ "main" ]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.HOSTNAME }}
      EC2_USERNAME: ${{ secrets.USER_NAME }}
    steps:
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
    # then you can run commands/scripts directly on the EC2 instance e.g.:
    - name: Create a new file on the EC2 instance with "hello-world"
      run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "\
       rm -rf Githubactiondemo && \
       git clone https://github.com/Shivshashyamankotia/Githubactiondemo.git && \
       cd Githubactiondemo && \
       rm -rf node_modules || true && \
       sudo npm install -g pm2 && \
       npm install && \
       pm2 start npm --name frontend -- start"

